services:
  - type: cron
    name: stream24news-backend
    env: python
    schedule: "30 18 * * *"  # Runs every day at 12:00 AM UTC
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app/main.py"
    envVars:
      - key: GOOGLE_CREDENTIALS
        value: 
